### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by cmartinotti** [maartenbreddels/flask-ipywidgets#26]
I just installed flask-ipywidget using pip. As I try to run any of the examples i get an error when i try to call flask_ipywidget.app():

I first get told that he is missing flask_sockets:
````
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\Flask\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\Anaconda3\envs\Flask\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\ProgramData\Anaconda3\envs\Flask\lib\site-packages\flask_ipywidgets\__init__.py", line 2, in <module>
    from flask_sockets import Sockets
ModuleNotFoundError: No module named 'flask_sockets'
````
so i pip install flask_sockets. Then though when I try to run any of the examples, when it gets to the definition of the app i get :
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\Labwest_1\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\Labwest_1\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Carlo\flask-ipywidgets\flask_ipywidgets\example1.py", line 5, in <module>
    app = flask_ipywidgets.app()
  File "C:\Users\Carlo\flask-ipywidgets\flask_ipywidgets\__init__.py", line 105, in app
    sockets.register_blueprint(websocket, url_prefix=prefix)
  File "C:\ProgramData\Anaconda3\envs\Labwest_1\lib\site-packages\flask_sockets.py", line 104, in register_blueprint
    blueprint.register(self, options, first_registration)
TypeError: register() takes 3 positional arguments but 4 were given
```
What am I doing wrong?

**Comment by javi600** [comment]
I have the same issue and I am stuck. Did you finally fix it?

**Comment by maartenbreddels** [comment]
my best guess is downgrading flask

**Comment by amoghtewari** [comment]
Nice guess, can confirm that downgrading flask to '1.1.2', jinja2 to'3.0.3' and itsdangerous to '2.0.1' worked for me.

**Comment by maartenbreddels** [comment]
Superseded by [https://github.com/widgetti/solara/](https://github.com/widgetti/solara/)
